### ISSUE TITLE
Add functionality to the signout button

### ISSUE THREAD

**Issue by SprocketCreations** [SprocketCreations/truck-rental#36]
### Tasks:
- [x] Create `/js/signout.js` and link it in /views/layouts/main.handlebars`
- [x] Add an event listener to the element with id=`signout-button` to `DELETE` `/signout`
- [x] Reload the page if successful
