### ISSUE TITLE
Add `/rent` route to API

### ISSUE THREAD

**Issue by SprocketCreations** [SprocketCreations/truck-rental#37]
### Tasks:
- [x] Create a new file `/controllers/api/rent.js`
- [x] Add route to `./rent.js` in `/controllers/api/index.js` at relative path `/rent`
- [x] Add PUT `/pickup` which updates the status of the rent to `pickedup`
- [x] Add PUT `/cancel` which updates the status of the rent to `canceled`
- [x] Add PUT `/return` which does the following:
### `/return`:
- [x] Change status of rent to `returned`
- [x] Increment the truck's odometer by the distance
- [ ] Calculate the payment as `hours * price per hour` + `distance * price per mile`
