### ISSUE TITLE
Truck view page features

### ISSUE THREAD

**Issue by SprocketCreations** [SprocketCreations/truck-rental#45]
### Tasks:
- [x] Add form to page to allow submission of rent
- [x] POST rent to `/api/reserve`
#### Set the following in the body:
- [x] `pickUpDate`
- [x] `hours`
- [x] `TruckId` (can be ripped from the url)
