### ISSUE TITLE
renter Dashboard problems

### ISSUE THREAD

**Issue by SprocketCreations** [SprocketCreations/truck-rental#47]
### Tasks
- [ ] Dropoff date is blank
- [x] Pickup button should PUT to `/api/rent/pickup/:rentId`
- [x] Cancel button should PUT to `/api/rent/cancel/:rentID`
- [x] Return button should redirect to `/truck/return`
