### ISSUE TITLE
Upgrade home page to use search features

### ISSUE THREAD

**Issue by SprocketCreations** [SprocketCreations/truck-rental#69]
### Situation:
The search form on the homepage currently does not do anything.
### Goals:
The user should be able to change the data in the form and have the list of trucks updated to reflect it.
### Tasks:
- [x] Make frontend reactive.
- [x] Create a new route `/api/search` to GET the truck data to display on the page given search query parameters.
- [x] Have changes to the form re-fetch `api/search` and regenerate the page.
- [x] Use Sequelize and JS on the server to filter down and sort the data before sending it to the client.
- [x] Ommit trucks that are unavailable during the requested timeslot.
